In [ ]:
# Task 4: Classification with Logistic Regression

In [ ]:
# 1.Choose a binary classification dataset

In [ ]:
#importing library

In [2]:
import pandas as pd
import numpy as np

In [3]:
# loading dataset

In [17]:
df=pd.read_csv("C:/Users/HP/Downloads/IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
# info of dataset

In [19]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [21]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [23]:
df.shape

(150, 5)

In [24]:
df.isna()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [25]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# 2.Train/test split and standardize features

In [ ]:
# importing library

In [16]:
from sklearn.model_selection import train_test_split

In [ ]:
# selecting the target and feature columns x=[feature column], y=[target column]

In [85]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['species']=le.fit_transform(df['species'])

In [86]:
X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df["species"]

In [87]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [88]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [89]:
# splitting the dataset 

In [90]:
X_train,X_test,y_train,y_test=train_test_split(X, y,test_size=0.25,random_state=42)

In [91]:
print("Training features:\n", X_train.head())
print("Training target:\n", y_train.head())

Training features:
      sepal_length  sepal_width  petal_length  petal_width
4             5.0          3.6           1.4          0.2
32            5.2          4.1           1.5          0.1
142           5.8          2.7           5.1          1.9
85            6.0          3.4           4.5          1.6
86            6.7          3.1           4.7          1.5
Training target:
 4      0
32     0
142    2
85     1
86     1
Name: species, dtype: int64


In [92]:
#  standardize features

In [93]:
# importing library

In [94]:
from sklearn.preprocessing import StandardScaler

In [95]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [96]:
# 3.Fit a Logistic Regression model

In [97]:
# importing library

In [98]:
from sklearn.linear_model import LogisticRegression

In [99]:
model=LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [100]:
# model parameters

In [101]:
model.classes_

array([0, 1, 2], dtype=int64)

In [102]:
model.intercept_

array([-0.39861014,  1.92599956, -1.52738942])

In [103]:
model.coef_

array([[-0.97466625,  1.08285601, -1.78340695, -1.66366618],
       [ 0.50731743, -0.30085977, -0.33028187, -0.68318633],
       [ 0.46734881, -0.78199623,  2.11368882,  2.34685251]])

In [104]:
model.predict_proba(X_test)

array([[8.07113310e-03, 8.11978018e-01, 1.79950849e-01],
       [9.41771713e-01, 5.82256334e-02, 2.65407131e-06],
       [4.82600797e-08, 3.25996074e-03, 9.96739991e-01],
       [8.90412771e-03, 6.71995071e-01, 3.19100801e-01],
       [1.39743358e-03, 6.56158334e-01, 3.42444233e-01],
       [8.85705402e-01, 1.14285326e-01, 9.27225008e-06],
       [6.06382521e-02, 8.78888459e-01, 6.04732889e-02],
       [7.02144023e-05, 5.67348298e-02, 9.43194956e-01],
       [4.79204144e-04, 4.91662564e-01, 5.07858232e-01],
       [2.05260341e-02, 9.01055965e-01, 7.84180009e-02],
       [8.42755669e-04, 1.70330527e-01, 8.28826718e-01],
       [9.04152913e-01, 9.58435581e-02, 3.52884651e-06],
       [9.30832472e-01, 6.91657317e-02, 1.79647229e-06],
       [9.10085758e-01, 8.99108799e-02, 3.36243952e-06],
       [9.81731978e-01, 1.82673647e-02, 6.56867940e-07],
       [1.36133481e-02, 6.28844743e-01, 3.57541909e-01],
       [3.45117854e-05, 2.95347851e-02, 9.70430703e-01],
       [1.74519745e-02, 9.13709

In [105]:
model.score(X_test,y_test)

0.9736842105263158

In [106]:
y_pred=model.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0], dtype=int64)

In [107]:
# 4.Evaluate with confusion matrix, precision, recall, ROC-AUC.

In [108]:
# importing library

In [109]:
from sklearn.metrics import(accuracy_score, confusion_matrix, classification_report, roc_auc_score)

In [110]:
# accuracy

In [111]:
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 0.9736842105263158


In [112]:
# confusion matrix

In [113]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[15  0  0]
 [ 0 10  1]
 [ 0  0 12]]


In [114]:
# classification report [precision,recall,f1 score]

In [115]:
target_names=['setosa','versicolor','virginica']

In [116]:
print("Classification Report:\n")
print(classification_report(y_test,y_pred,target_names=target_names))

Classification Report:

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      0.91      0.95        11
   virginica       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [117]:
# ROC-AUC

In [118]:
from sklearn.preprocessing import label_binarize
y_test_bin=label_binarize(y_test,classes=[0,1,2])
y_test_bin

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [125]:
y_proba=model.predict_proba(X_test)

In [126]:
y_test_bin=label_binarize(y_test,classes=[0, 1, 2])

In [127]:
roc_auc=roc_auc_score(y_test_bin,y_proba,average='macro',multi_class='ovr')
print(f"Multiclass ROC-AUC Score: {roc_auc:.4f}")

Multiclass ROC-AUC Score: 1.0000


In [ ]:
# 5.Tune threshold and explain sigmoid function

In [ ]:
# Get predicted probabilities

In [129]:
y_proba1=model.predict_proba(X_test)[:,1]
y_proba1

array([0.81197802, 0.05822563, 0.00325996, 0.67199507, 0.65615833,
       0.11428533, 0.87888846, 0.05673483, 0.49166256, 0.90105596,
       0.17033053, 0.09584356, 0.06916573, 0.08991088, 0.01826736,
       0.62884474, 0.02953479, 0.91370953, 0.78524818, 0.03058089,
       0.05818105, 0.30847442, 0.06512038, 0.04402375, 0.07129814,
       0.04456059, 0.07369413, 0.02265658, 0.11926138, 0.09218244,
       0.00880261, 0.00851301, 0.81343877, 0.03708684, 0.0281305 ,
       0.13385027, 0.74068271, 0.04910897])

In [130]:
# Set custom threshold

In [133]:
threshold=0.4
y_pred_thresh=(y_proba1>=threshold).astype(int)
y_pred_thresh

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [134]:
print(confusion_matrix(y_test, y_pred_thresh))

[[15  0  0]
 [ 0 11  0]
 [12  0  0]]


In [142]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score
print("Precision:", precision_score(y_test, y_pred_thresh, average='macro',zero_division=0))
print("Recall:", recall_score(y_test, y_pred_thresh, average='macro',zero_division=0))

Precision: 0.5185185185185185
Recall: 0.6666666666666666


In [ ]:
# sigmoid function

In [ ]:
🔹 What is the Sigmoid Function?
Logistic Regression outputs a linear combination of features:
z=w0+w1x1+w2x2.....+wnxn
But this 
z can be any real number — positive, negative, or zero.
The sigmoid function converts this z into a probability between 0 and 1.
z -> +infinity,sigmoid -> 1(probability near 1)
z -> -infinity,sigmoid -> 0(probability near 0)
z -> 0,sigmoid ->0.5
This output represents the probability that the instance belongs to the positive class (class 1).